apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hive-role-binding
roleRef:
  kind: Role
  name: hive-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.name.hive.serviceAccount }}
  namespace: {{ .Release.Namespace }}
