{{ if .Values.create.metastore -}}
apiVersion: v1
kind: Service
metadata:
  #namespace: hivemr3
  name: {{ .Values.name.metastore.service }}
spec:
  clusterIP: None
  selector:
    hivemr3_app: metastore
  ports:
  - name: tcp
    port: {{ .Values.metastore.port }}
{{ end }}