apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-role-binding
roleRef:
  kind: Role
  name: worker-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.name.mr3.workerServiceAccount }}
  namespace: {{ .Release.Namespace }}
