apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name.hive.workerSecret }}
type: Opaque
data:
  {{- if .Values.hive.createSecret }}
  {{- (.Files.Glob "key/*").AsSecrets | nindent 2 }}
  {{- end }}
