# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM azul/zulu-openjdk-centos:17.0.8.1-17.44.53

USER root

# create directories under /opt/mr3-run

RUN mkdir -p /opt/mr3-run && \
    mkdir -p /opt/mr3-run/scratch-dir && \
    mkdir -p /opt/mr3-run/work-dir && \
    mkdir -p /opt/mr3-run/work-local-dir && \
    mkdir -p /opt/mr3-run/key && \
    mkdir -p /opt/mr3-run/conf && \
    mkdir -p /opt/mr3-run/hive/tmp && \
    mkdir -p /opt/mr3-run/hive/run-result 

RUN yum install -y epel-release && yum install -y procps wget snappy-devel libzstd-devel && yum clean all

# copy files 

COPY common-setup.sh /opt/mr3-run/
COPY hadoop/hadoop-setup.sh /opt/mr3-run/hadoop/
COPY hive/*.sh /opt/mr3-run/hive/
COPY mr3/mr3-setup.sh /opt/mr3-run/mr3/
COPY tez/tez-setup.sh /opt/mr3-run/tez/

COPY hadoop/apache-hadoop /opt/mr3-run/hadoop/apache-hadoop
COPY hive/apache-hive/lib/hive-exec-3.1.3.jar /opt/mr3-run/hive/apache-hive/lib/
COPY hive/apache-hive/lib/hive-llap-common-3.1.3.jar /opt/mr3-run/hive/apache-hive/lib/
COPY hive/apache-hive/lib/hive-llap-server-3.1.3.jar /opt/mr3-run/hive/apache-hive/lib/
COPY hive/apache-hive/lib/hive-llap-tez-3.1.3.jar /opt/mr3-run/hive/apache-hive/lib/
COPY lib /opt/mr3-run/lib
COPY mr3/mr3lib /opt/mr3-run/mr3/mr3lib
COPY tez/tezjar /opt/mr3-run/tez/tezjar

# set environments

WORKDIR /opt/mr3-run/hive

ARG UID=1000
RUN adduser --no-create-home --disabled-login --gecos "" --uid $UID hive && \
    chown hive /opt/mr3-run/scratch-dir && \
    chown hive /opt/mr3-run/work-dir && \
    chown hive /opt/mr3-run/work-local-dir && \
    chown hive /opt/mr3-run/hive && \
    chown hive /opt/mr3-run/hive/tmp && \
    chown hive /opt/mr3-run/hive/run-result

USER hive

