apiVersion: v1
kind: Service
metadata:
  # namespace: hivemr3
  name: ranger
spec:
  type: LoadBalancer
  ports:
  - name: ranger-admin-http
    protocol: TCP
    port: {{ .Values.ranger.httpPort }}
    targetPort: 6080
  - name: ranger-admin-https
    protocol: TCP
    port: {{ .Values.ranger.httpsPort }}
    targetPort: 6182
  - name: solr
    protocol: TCP
    port: {{ .Values.ranger.solrPort }}
    targetPort: 6083
  selector:
    hivemr3_app: ranger
  externalIPs:
  - {{ .Values.ranger.externalIp }}
