apiVersion: v1
appVersion: 3.0.0
description: The Apache Hive ™ data warehouse software facilitates reading, writing, and managing large datasets
  residing in distributed storage using SQL. Structure can be projected onto data already in storage. A command 
  line tool and JDBC driver are provided to connect users to Hive.
home: https://hive.apache.org/
icon: https://hive.apache.org/images/hive_logo_medium.jpg
maintainers:
- email: meloyang@amazon.com
  name: meloyang
name: hive-metastore
sources:
- https://github.com/apache/hive
- https://github.com/gradiant/charts
- https://github.com/amommendes/helm-hive-metastore
version: 1.2.0
