apiVersion: v1
kind: Service
metadata:
  namespace: hivemr3
  name: timelineserver
spec:
  type: LoadBalancer
  ports:
  - name: ats-http
    protocol: TCP
    port: 8188
    targetPort: 8188
  - name: ats-https
    protocol: TCP
    port: 8190
    targetPort: 8190
  selector:
    hivemr3_app: ats
  externalIPs:
  - 1.1.1.1
