apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: hivemr3
  name: hivemr3-ats
spec:
  serviceName: timelineserver
  replicas: 1
  selector:
    matchLabels:
      hivemr3_hive_source: hivesrc3
      hivemr3_app: ats
  template:
    metadata:
      namespace: hivemr3
      name: hivemr3-ats
      labels:
        hivemr3_hive_source: hivesrc3
        hivemr3_app: ats
        mr3-pod-role: master-role
    spec:
      restartPolicy: Always
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  hivemr3_app: metastore
      containers:
      - image: mr3project/ats-2.7.7:latest
        command: ["/opt/mr3-run/ats/timeline-service.sh"]
        imagePullPolicy: Always
        name: timelineserver
        env:
        - name: ATS_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: client-ats-config
              key: ats-secret-key
        resources:
          requests:
            cpu: 1
            memory: 4Gi
          limits:
            cpu: 1
            memory: 4Gi
        ports:
        - containerPort: 8188
          protocol: TCP
        - containerPort: 8190
          protocol: TCP
        volumeMounts:
        - name: env-k8s-volume
          mountPath: /opt/mr3-run/ats/env.sh
          subPath: env.sh
        - name: ats-conf-k8s-volume
          mountPath: /opt/mr3-run/ats/conf/
          readOnly: true
        - name: ats-key-k8s-volume
          mountPath: /opt/mr3-run/ats/key/
          readOnly: true
        - name: work-dir-volume
          mountPath: /opt/mr3-run/ats/work-dir/
      volumes:
      - name: env-k8s-volume
        secret:
          secretName: env-secret
      - name: ats-conf-k8s-volume
        configMap:
          name: hivemr3-ats-conf-configmap
      - name: ats-key-k8s-volume
        secret:
          secretName: hivemr3-ats-secret
      - name: work-dir-volume
        persistentVolumeClaim:
          claimName: workdir-pvc-ats
