apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hivemr3
  name: hivemr3-hiveserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      hivemr3_hive_source: hivesrc3
      hivemr3_app: hiveserver2
  template:
    metadata:
      namespace: hivemr3
      name: hivemr3-hiveserver2
      labels:
        hivemr3_hive_source: hivesrc3
        hivemr3_app: hiveserver2
        mr3-pod-role: master-role
    spec:
      serviceAccountName: hive-service-account
      restartPolicy: Always
      hostAliases:
      - ip: "1.1.1.1"
        hostnames:
        - "red0"
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  hivemr3_app: metastore
      containers:
      - image: mr3project/hive3:1.10
        command: ["/opt/mr3-run/hive/hiveserver2-service.sh"]
        args: ["start", "--kubernetes"]
        imagePullPolicy: Always
        name: hiveserver2
        env:
        - name: CLIENT_TO_AM_TOKEN_KEY
          valueFrom:
            configMapKeyRef:
              name: client-am-config
              key: key
        - name: MR3_APPLICATION_ID_TIMESTAMP
          valueFrom:
            configMapKeyRef:
              name: client-am-config
              key: timestamp
        - name: MR3_SHARED_SESSION_ID
          valueFrom:
            configMapKeyRef:
              name: client-am-config
              key: mr3sessionid
        - name: ATS_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: client-am-config
              key: ats-secret-key
        resources:
          requests:
            cpu: 2
            memory: 16Gi
          limits:
            cpu: 2
            memory: 16Gi
        ports:
        - containerPort: 9852
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 9852
          initialDelaySeconds: 30
          periodSeconds: 60
        livenessProbe:
          tcpSocket:
            port: 9852
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: env-k8s-volume
          mountPath: /opt/mr3-run/env.sh
          subPath: env.sh
        - name: conf-k8s-volume
          mountPath: /opt/mr3-run/conf/
          readOnly: true
        - name: key-k8s-volume
          mountPath: /opt/mr3-run/key/
          readOnly: true
        - name: am-local-k8s-volume
          mountPath: /opt/mr3-run/am-local-dir
        - name: work-dir-volume
          mountPath: /opt/mr3-run/work-dir
        - name: hiveserver2-ranger-policy-k8s-volume
          mountPath: /opt/mr3-run/hiveserver2-ranger-policycache
        # - name: host-lib-volume
        #   mountPath: /opt/mr3-run/host-lib
      volumes:
      - name: env-k8s-volume
        secret:
          secretName: env-secret
      - name: conf-k8s-volume
        configMap:
          name: hivemr3-conf-configmap
      - name: key-k8s-volume
        secret:
          secretName: hivemr3-keytab-secret
      - name: am-local-k8s-volume
        emptyDir: {} 
      - name: work-dir-volume
        persistentVolumeClaim:
          claimName: workdir-pvc
      - name: hiveserver2-ranger-policy-k8s-volume
        emptyDir: {}
      # - name: host-lib-volume
      #   hostPath:
      #     path: /home/ec2-user/lib
      #     type: Directory
