apiVersion: v1
kind: Service
metadata:
  namespace: hivemr3
  name: hiveserver2
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9852
    targetPort: 9852
    name: thrift
  - protocol: TCP
    port: 10001
    targetPort: 10001
    name: http
  selector:
    hivemr3_app: hiveserver2
  externalIPs:
  - 1.1.1.1
