apiVersion: v1
kind: Service
metadata:
  namespace: hivemr3
  name: ranger
spec:
  type: LoadBalancer
  ports:
  - name: ranger-admin-http
    protocol: TCP
    port: 6080
    targetPort: 6080
  - name: ranger-admin-https
    protocol: TCP
    port: 6182
    targetPort: 6182
  - name: solr
    protocol: TCP
    port: 6083
    targetPort: 6083
  selector:
    hivemr3_app: ranger
  externalIPs:
  - 1.1.1.1
