apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hivemr3
  name: workdir-pvc-ats
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
