apiVersion: v1
kind: PersistentVolume
metadata:
  name: workdir-pv-ranger
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: "1.1.1.1"
    path: "/work/nfs/ranger"
